import { priceSeriesFor, type BunkerPriceSnapshot } from "./bunkerEvents";
import { readCsv } from "./csv";
import { resolvePricePort } from "./ports";
import { latestPoint, trimNulls } from "./series";
import { VESSEL_GRADES, type Grade, type PortPrices, type PricePoint } from "./types";

// Re-exported so server callers have one import site for price helpers.
export { latestPoint, previousPoint } from "./series";

/** Pseudo-port holding the Brent benchmark, offered as a chart overlay. */
export const BRENT_KEY = "__BRENT";

/**
 * Deliberately a literal list rather than a glob of data/pricing/.
 *
 * Everything reached from here flows into bunkerPriceSnapshot() and prices a
 * bunker stem, so what belongs in this array is a decision, not a directory
 * listing. data/pricing/ also holds bunker_basis.csv, which is provenance for
 * the modelled columns and not a price sheet — a readdir would try to parse it
 * as one.
 *
 * Note that these files are no longer purely assessed: the 23 ports nobody
 * quotes carry modelled columns generated by scripts/gen-modelled-prices.mjs,
 * mixed in under the same header convention. Nothing downstream distinguishes
 * them. See data/README.md.
 */
const PRICE_FILES = [
  "pricing/VLSFO Prices.csv",
  "pricing/HSGO Prices.csv",
  "pricing/LSMGO_MGO Prices.csv",
  "pricing/MDO Prices.csv",
  "pricing/LNG Prices.csv",
  "pricing/Biofuel Prices.csv",
  "pricing/Methanol Prices.csv",
];

/**
 * Grade suffixes, longest first so "MEOH VLSFOe" is matched before "MEOH"
 * and never mistaken for a plain VLSFO column.
 *
 * "LSMGO" must stay ahead of "MGO" for the same reason: the two are distinct
 * products on the Chief Engineer's sheet, and "<PORT> LSMGO" ends in "MGO".
 */
const GRADE_SUFFIXES: Array<[string, Grade]> = [
  ["MEOH VLSFOE", "MEOH_VLSFOe"],
  ["MEOH MGOE", "MEOH_MGOe"],
  ["MEOH", "MEOH"],
  ["HSFO", "HSFO"],
  ["VLSFO", "VLSFO"],
  ["LSMGO", "LSMGO"],
  ["MGO", "MGO"],
  ["MDO", "MDO"],
  ["LNG", "LNG"],
  ["B24", "B24"],
  ["B40", "B40"],
];

export type PriceIndex = Map<string, Map<Grade, PricePoint[]>>;

let indexCache: PriceIndex | null = null;

/**
 * Split a pricing column header into its port and grade, e.g.
 * "LA LongBeach HSFO" -> { portKey: "USLGB", grade: "HSFO" }.
 * Returns null for headers whose port is not in the alias table.
 */
function parseHeader(header: string): { portKey: string; grade: Grade } | null {
  const upper = header.trim().toUpperCase().replace(/\s+/g, " ");
  for (const [suffix, grade] of GRADE_SUFFIXES) {
    if (upper === suffix || upper.endsWith(` ${suffix}`)) {
      const prefix = upper.slice(0, upper.length - suffix.length).trim();
      const portKey = resolvePricePort(prefix);
      return portKey ? { portKey, grade } : null;
    }
  }
  return null;
}

function buildIndex(): PriceIndex {
  const index: PriceIndex = new Map();

  const push = (portKey: string, grade: Grade, points: PricePoint[]) => {
    const trimmed = trimNulls(points);
    if (trimmed.length === 0) return;
    let byGrade = index.get(portKey);
    if (!byGrade) {
      byGrade = new Map();
      index.set(portKey, byGrade);
    }
    byGrade.set(grade, trimmed);
  };

  for (const file of PRICE_FILES) {
    const { headers, rows } = readCsv(file);
    // Source rows are newest-first; charts need oldest-first.
    const ordered = [...rows].reverse();

    for (const header of headers) {
      if (header === "Date") continue;
      const parsed = parseHeader(header);
      if (!parsed) continue;

      const points: PricePoint[] = [];
      for (const row of ordered) {
        const date = (row["Date"] ?? "").trim();
        if (!date) continue;
        const raw = (row[header] ?? "").trim();
        const value = raw === "" ? null : Number(raw);
        points.push({
          date,
          value: value === null || !Number.isFinite(value) ? null : value,
        });
      }
      push(parsed.portKey, parsed.grade, points);
    }
  }

  // Brent, in $/mt so it shares the chart's y-axis with the fuel grades.
  // The raw $/bbl "Brent" column is deliberately ignored.
  const brent = readCsv("pricing/Brent Prices.csv");
  const brentPoints: PricePoint[] = [...brent.rows].reverse().flatMap((row) => {
    const date = (row["Date"] ?? "").trim();
    if (!date) return [];
    const raw = (row["BrentPMT"] ?? "").trim();
    const value = raw === "" ? null : Number(raw);
    return [
      { date, value: value === null || !Number.isFinite(value) ? null : value },
    ];
  });
  push(BRENT_KEY, "BRENT", brentPoints);

  return index;
}

export function getPriceIndex(): PriceIndex {
  if (!indexCache) indexCache = buildIndex();
  return indexCache;
}

/** All grades for one port, as a plain object ready to serialise. */
export function getPortPrices(portKey: string): PortPrices {
  const byGrade = getPriceIndex().get(portKey);
  if (!byGrade) return {};
  const out: PortPrices = {};
  for (const [grade, points] of byGrade) out[grade] = points;
  return out;
}

export function getBrentSeries(): PricePoint[] {
  return getPriceIndex().get(BRENT_KEY)?.get("BRENT") ?? [];
}

/**
 * Latest real assessment per port, for the two grades vessels actually stem.
 *
 * Built once server-side and shipped as props: it is a few dozen numbers, so
 * the arrival toasts need no fetch, and lib/bunkerEvents.ts stays free of the
 * CSV reader.
 *
 * Not every figure here is an assessment. Only three of the twenty-six ports
 * where this fleet bunkers are actually quoted — Singapore, Busan and Shanghai.
 * The other twenty-three carry modelled columns: an assessed hub series plus a
 * documented basis, generated by scripts/gen-modelled-prices.mjs from
 * data/pricing/bunker_basis.csv and written into the same wide CSVs.
 *
 * This function cannot tell the two apart, and neither can anything it feeds.
 * A stem valued at Chittagong is therefore priced off Singapore plus a judgment
 * differential, and reads in the UI exactly like a quoted one. That is a
 * deliberate choice about where the numbers live, not an oversight — but any
 * total built from this snapshot is part modelled, and saying so belongs
 * wherever those totals are presented.
 *
 * Gaps are still gaps: a port absent here means no figure at all, never zero.
 * As of the current movement file every stem does resolve, because the
 * generator now picks its stem grade by what the port can supply — Shanghai
 * has no HSFO column and no longer receives HSFO stems. That is a property
 * of the data, not a guarantee of this function.
 */
export function bunkerPriceSnapshot(): BunkerPriceSnapshot {
  const snapshot: BunkerPriceSnapshot = {};

  for (const [portKey, byGrade] of getPriceIndex()) {
    if (portKey === BRENT_KEY) continue;

    for (const vesselGrade of VESSEL_GRADES) {
      // Which column values this tank depends on the port: the distillate tank
      // is priced as LSMGO where the port sells the 0.10% grade, MGO elsewhere.
      const series = priceSeriesFor(vesselGrade, portKey);
      const points = byGrade.get(series);
      if (!points) continue;

      // Several columns stop being quoted before the file ends, so take the
      // last point that actually carries a value rather than the last row.
      const point = latestPoint(points);
      if (!point || point.value === null) continue;

      const entry = snapshot[portKey] ?? (snapshot[portKey] = {});
      entry[vesselGrade] = { value: point.value, date: point.date, series };
    }
  }

  return snapshot;
}

/** Newest quote date anywhere in the dataset — the header's "as of". */
export function latestDataDate(): string | null {
  let latest: string | null = null;
  for (const byGrade of getPriceIndex().values()) {
    for (const points of byGrade.values()) {
      const p = latestPoint(points);
      if (p && (latest === null || p.date > latest)) latest = p.date;
    }
  }
  return latest;
}
