import { GRADE_ORDER } from "./colors";
import { num, readCsv, str } from "./csv";
import { getPortPrices } from "./prices";
import { latestPoint } from "./series";
import type { Grade, PortMarket, SupplierOffer, SupplierTier } from "./types";

/**
 * The supplier side of a port: who quotes, and how far off the assessment.
 *
 * Imports node:fs through readCsv and must never be pulled into a client
 * bundle — the same rule that governs prices.ts and schedules.ts. It is reached
 * only from the /api/prices/[portKey] route.
 *
 * Offers carry a differential, not a price. Resolving `baseline + diff` here
 * rather than materialising prices into the CSV is what keeps them honest: a
 * price refresh moves every quote with it, and there is no generator to re-run.
 * The trade-off is that a grade with no assessment has no market at all, which
 * is the correct answer rather than a missing one.
 *
 * None of these figures are sourced. The PIL supplier list carries no prices,
 * ports or grades; the differentials and delivery terms are generated by
 * scripts/gen-supplier-offers.mjs. Anything presenting them must say so.
 */

const SUPPLIERS_FILE = "contracts/suppliers.csv";
const OFFERS_FILE = "contracts/supplier_offers.csv";

interface SupplierMeta {
  tier: SupplierTier;
  tierLabel: string;
}

interface RawOffer {
  grade: Grade;
  supplier: string;
  diff: number;
  deliveryMode: string;
  minMt: number;
  maxMt: number;
  leadTimeDays: number;
  paymentTermsDays: number;
  pumpRateMtPerHour: number;
  availability: string;
}

/** portKey -> the offers quoted there, in file order. */
type OfferIndex = Map<string, RawOffer[]>;

let offerCache: OfferIndex | null = null;
let metaCache: Map<string, SupplierMeta> | null = null;

function getSupplierMeta(): Map<string, SupplierMeta> {
  if (metaCache) return metaCache;

  const meta = new Map<string, SupplierMeta>();
  for (const row of readCsv(SUPPLIERS_FILE).rows) {
    const name = str(row, "supplier");
    const tier = num(row, "tier");
    if (!name || tier === null) continue;

    meta.set(name, {
      tier: tier as SupplierTier,
      tierLabel: str(row, "tier_label") ?? "",
    });
  }

  metaCache = meta;
  return meta;
}

function buildOfferIndex(): OfferIndex {
  const index: OfferIndex = new Map();

  for (const row of readCsv(OFFERS_FILE).rows) {
    const portKey = str(row, "Port_Code");
    const grade = str(row, "Grade") as Grade | null;
    const supplier = str(row, "Supplier");
    const diff = num(row, "Offer_Basis_USD_Per_MT");

    // A blank differential is not parity — it is a row that says nothing, and
    // Number("") is 0, so emptiness is checked before conversion. Such a row is
    // dropped rather than quoted at the assessment.
    if (!portKey || !grade || !supplier || diff === null) continue;

    const offers = index.get(portKey) ?? [];
    offers.push({
      grade,
      supplier,
      diff,
      deliveryMode: str(row, "Delivery_Mode") ?? "Barge",
      minMt: num(row, "Min_Lifting_MT") ?? 0,
      maxMt: num(row, "Max_Lifting_MT") ?? 0,
      leadTimeDays: num(row, "Lead_Time_Days") ?? 0,
      paymentTermsDays: num(row, "Payment_Terms_Days") ?? 0,
      pumpRateMtPerHour: num(row, "Pump_Rate_MT_Per_Hour") ?? 0,
      availability: str(row, "Availability") ?? "Enquire",
    });
    index.set(portKey, offers);
  }

  return index;
}

function getOfferIndex(): OfferIndex {
  if (!offerCache) offerCache = buildOfferIndex();
  return offerCache;
}

/**
 * Every fuel type this port has a market in, ordered as the tiles and chart
 * order them, each with its baseline and the panel quoting against it.
 *
 * The baseline is the last point that actually carries a value, not the last
 * row — several columns stop being quoted before the file ends. This is the
 * same rule bunkerPriceSnapshot() applies, but across every grade rather than
 * only the two the fleet stems.
 */
export function getPortMarkets(portKey: string): PortMarket[] {
  const offers = getOfferIndex().get(portKey);
  if (!offers || offers.length === 0) return [];

  const prices = getPortPrices(portKey);
  const meta = getSupplierMeta();

  const byGrade = new Map<Grade, SupplierOffer[]>();
  const baselines = new Map<Grade, { value: number; date: string }>();

  for (const offer of offers) {
    let baseline = baselines.get(offer.grade);

    if (!baseline) {
      const point = latestPoint(prices[offer.grade] ?? []);
      // Nothing to spread against, so there is no quote to make. A price is
      // never invented and never falls back to zero.
      if (!point || point.value === null) continue;
      baseline = { value: point.value, date: point.date };
      baselines.set(offer.grade, baseline);
    }

    const supplierMeta = meta.get(offer.supplier);
    const list = byGrade.get(offer.grade) ?? [];
    list.push({
      supplier: offer.supplier,
      tier: supplierMeta?.tier ?? 2,
      tierLabel: supplierMeta?.tierLabel ?? "",
      price: Math.round((baseline.value + offer.diff) * 100) / 100,
      diff: offer.diff,
      deliveryMode: offer.deliveryMode,
      minMt: offer.minMt,
      maxMt: offer.maxMt,
      leadTimeDays: offer.leadTimeDays,
      paymentTermsDays: offer.paymentTermsDays,
      pumpRateMtPerHour: offer.pumpRateMtPerHour,
      availability: offer.availability,
    });
    byGrade.set(offer.grade, list);
  }

  return [...byGrade.entries()]
    .sort(([a], [b]) => GRADE_ORDER.indexOf(a) - GRADE_ORDER.indexOf(b))
    .map(([grade, list]) => ({
      grade,
      baseline: baselines.get(grade) ?? null,
      // Cheapest first: the panel is read as a buying decision, not a series.
      offers: [...list].sort(
        (x, y) => x.price - y.price || x.supplier.localeCompare(y.supplier),
      ),
    }));
}
